### ISSUE TITLE
is it legal?

### ISSUE THREAD

**Issue by zhuojl** [Monlogue/keruyun#4]
may be you should delete this repository

**Comment by Monlogue** [comment]
I don't think it's illegal for me to develop an interface based on an open platform.
https://gldopen.keruyun.com/apidoc/


andy13134@outlook.com
 
From: zhuojl
Date: 2020-04-27 13:58
To: Monlogue/keruyun
CC: Subscribed
Subject: [Monlogue/keruyun] is it legal? (#4)
may be you should delete this repository

**Comment by zhuojl** [comment]
you are right. i was surprised by your description without careful reading.

**Comment by Monlogue** [comment]
Thank you, thank you for understanding



andy13134@outlook.com
 
From: zhuojl
Date: 2020-04-28 09:03
To: Monlogue/keruyun
CC: Monlogue; Comment
Subject: Re: [Monlogue/keruyun] is it legal? (#4)
you are right. i was surprised by your description without careful reading.
